### ISSUE TITLE
2024년 처서 날짜 및 절입시간이 이상해요!

### ISSUE THREAD

**Issue by kunwis** [OOPS-ORG-PHP/Lunar#1]
안녕하세요.

공개해 주신 진짜만세력을 설치하여 분석하던 중 2024년 처서의 정보가 이상해서 문의드립니다.

진짜 만세력  : AD 2024년 8월 23일 0시 12분
한국천문연구원 : AD 2024년 8월 22일 23시 55분

다른 절기들은 정확하게 맞는것 같은데 지금까지 이것만 상이하게 나오네요.
이유를 알아야 수정을 할텐데 너무 전문적인 지식이라 근접할 수가 없네요.
시간 나실때 한번 봐주시기 바랍니다. 공개된 만세력중에 최고입니다.
감사합니다.

**Comment by Joungkyun** [comment]
일단, 진짜 만세력 [고영창님의 홈페이지](http://afnmp3.homeip.net/~kohyc/calendar/index.cgi)에서 정보를 찾아보면, 만세력 정보로 2024년 처서의 정보가 "2024-08-22 23:48" 으로 나옵니다. 천문 연구원 정보 보다 7분 정도 빠르게 나오네요.

문제는, 고영창님이 공개하신 코드 (perl 0.92, pascal 0.93) 에서는 결과 값이 "2024-08-23 0:12" 으로 나옵니다. 일단 php porting 이 잘못된 것은 아니고, original code 의 이슈로 봐야 할 것 같네요
그리고 [버전 history](http://afnmp3.homeip.net/~kohyc/calendar/cal20000.html) 에서 보면, 0.93 이 후에는 Julian date 표시하는 변경 사항 밖에는 없다고 나옵니다.

그런데, cgi version 에서 코드를 보면 웹용 cgi 가 month.cgi 로 되어 있는데, 홈페이지 상에서는 month_new.cgi 로 운영이 되고 있습니다.

아마, 0.95 버전 이 후에, 계산 알고리즘에 업데이트가 있었던 것으로 보여 지나, 그 변경 사항은 공개가 안된 것으로 보입니다.

그러므로, 이 부분은 고영창님이 공개를 해 주시기 전에는 고치기는 힘들 것으로 보여집니다. 이를 픽스할 수있는 방법은, 천문 연구원의 절기 값을 database 화 해서 억지로 반영을 할 수 밖에 없을 것 같네요.


일단, 현재 코드는 perl 0.92 버전으로 작성된 것인데, 이 문제가 0.93에서 변경된 것인지 확인하기 위하여, pascal (0.93) code 와 비교를 하여 diff 를 만들어 본 결과는 다음과 같습니다.

```diff
diff -urNp ./Lunar/Lunar_API.php.org ./Lunar/Lunar_API.php
--- ./Lunar/Lunar_API.php.org     2024-08-24 02:29:32.420464330 +0900
+++ ./Lunar/Lunar_API.php       2024-08-24 05:06:25.728023210 +0900
@@ -334,7 +334,28 @@ Class Lunar_API {
                        $ppp2 = $pp2 - 1;

                        for ( $k = $ppp1; $k <= $ppp2; $k++ ) {
-                               if ( $k == -2000 && $ppp2 > 1990 ) {
+                               if ( $k == -9000 && $ppp2 > 1990 ) {
+                                       $dis += 4014377;
+                                       $k = 1991;
+                               } else if ( $k == -8000 && $ppp2 > 1990 ) {
+                                       $dis += 3649135;
+                                       $k = 1991;
+                               } else if ( $k == -7000 && $ppp2 > 1990 ) {
+                                       $dis += 3283893;
+                                       $k = 1991;
+                               } else if ( $k == -6000 && $ppp2 > 1990 ) {
+                                       $dis += 2918651;
+                                       $k = 1991;
+                               } else if ( $k == -5000 && $ppp2 > 1990 ) {
+                                       $dis += 2553408;
+                                       $k = 1991;
+                               } else if ( $k == -4000 && $ppp2 > 1990 ) {
+                                       $dis += 2188166;
+                                       $k = 1991;
+                               } else if ( $k == -3000 && $ppp2 > 1990 ) {
+                                       $dis += 1822924;
+                                       $k = 1991;
+                               } else if ( $k == -2000 && $ppp2 > 1990 ) {
                                        $dis += 1457682;
                                        $k = 1991;
                                } else if ( $k == -1750 && $ppp2 > 1990 ) {
@@ -438,7 +459,6 @@ Class Lunar_API {
         */
        protected function getdatebymin ($tmin, $uyear, $umonth, $uday, $uhour, $umin) {
                $y1 = $mo1 = $d1 = $h1 = $mi1 = $t = 0;
-
                $y1 = $uyear - $this->div ($tmin, 525949);

                if ( $tmin > 0 ) {
@@ -676,14 +696,16 @@ Class Lunar_API {
                );

                # 이거 고민좀 해 봐야 할 듯!!
+               # perl 과 php 의 음수의 나머지 결과값이 다르다! --;
                #$monthmin100 = $displ2min % 525949;
                #$monthmin100 = 525949 - $monthmin100;
-               $monthmin100 = ($displ2min % 525949) * -1;
+               $monthmin100 = $displ2min % 525949;
+               if ( $monthmin100 < 0 ) $monthmin100 *= -1;

                if ( $monthmin100 < 0 )
                        $monthmin100 += 525949;
                else if ( $monthmin100 >= 525949 )
-                       $monthmin100 = $monthmin - 525949;
+                       $monthmin100 -= 525949;

                $i = $so24month % 12 - 2;
                if ( $i == -2 ) $i = 10;
```

딱.. 이 부분만 추가 된 것 같네요.

> 망(음력보름)시간이 추가되었습니다. 이와 함께 해당 보름날의 월식여부도 추가되었습니다. 합삭시간과 망시간 다음에 나오는 소수점 2자리의 실수는 황백교점과 해당시점의 태양의 황경과의 각도 차이로 각도차이의 범위는 -90~+90도 입니다.

이 부분은 조만간 업데이트 할 예정이고, 천문 연구원의 절기 값은 현재 database 를 구할 수 있는 2021~2026년 까지의 절기 data 를 처리하고 있는  [KAIS_Lunar](https://github.com/OOPS-ORG-PHP/KASI-Lunar) package 를 통해 관리할 수 있도록 업데이트 해 보겠습니다.

P.S.
진짜 만세력을 사용함에 있어서, 진짜 만세력은 모든 값을 계산에 의해서 하게 됩니다. 문제는 이 계산이 시간이 지남에 따라 오차가 발생할 수 있다는 것이죠. 즉 한국 천문 연구원의 값과 오차는 어쩔 수 없는 부분 입니다. 천문 연구원은 매년 측정을 해서 값을 보정하기 때문에 이 보정에 의한 차이가 발생할 수 밖에 없습니다. 다만 실제로 시간차는 20여분 내외이지만 하루가 넘어가는 날에서 오차가 이렇게 발생하면 날자가 달라지므로, 이를 보정 하기 위해 진짜 만세력의 php package 는 KAIS_Lunar 라는 패키지를 통해 보정을 하는데요. 절기값도 여기에 반영을 해 볼까 합니다. 일단 고영창님의 알고리즘은 천문학에 아주 해박한 지식이 있지 않는한은, 고영창님 외에는 수정을 할 수 없을 것 같거든요 --;

**Comment by Joungkyun** [comment]
KASI-Lunar [2.0.0 release](https://github.com/OOPS-ORG-PHP/KASI-Lunar/releases/tag/2.0.0)
- support new season method with 한국천문연구원 절기 데이터 (2004 ~ 2026)

**Comment by Joungkyun** [comment]
KASI-Lunar 절기 데이터 기능 추가 ([@1a43bab](https://github.com/OOPS-ORG-PHP/Lunar/commit/1a43babc45e12789965ca3ba96a7275d5da964e0))

repository 에 code 는 반영이 되었고, 금주내로 2.0.1 release 예정 입니다.

**Comment by kunwis** [comment]
더운날 노고가 많으십니다.
친절한 답변 감사드리오며 조금더 다듬어 지면 아주 훌륭한 작품이 될것 같네요.
프로그램을 뜯어봐도 뭔지는 몰라도 두분다 존경스럽습니다.
fullcalendar 라이브러리에 적용해 보고 있는데 2050년 이전에는 0.15초 이던게
넘어가니 달을 넘기면 응답속도가 1초를 넘어 버리네요. 

음력:2053-04-19
평달 | 28수:규(奎)
계유년 정사월 임신일
癸酉年 丁巳月 壬申日
일별띠 : 원숭이[신:申]
별자리 : 쌍둥이자리
꽃말 : 메리골드
망종(절입:14시 12분)

음력:2053-04-20
평달 | 28수:수(婁)
계유년 무오월 계유일
癸酉年 戊午月 癸酉日
일별띠 : 닭[유:酉]
별자리 : 쌍둥이자리
꽃말 : 노랑 붓꽃
현충일

음력:2053-05-15
큰달 | 28수:위(危)
계유년 무오월 정유일
癸酉年 戊午月 丁酉日
일별띠 : 닭[유:酉]
별자리 : 게자리
꽃말 : 인동
손없는 날

이런정보들을 뿌려서 그런지 속도가 문제네요.
관심가져주셔서 고맙고 늘 건강하세요.
감사합니다.

**Comment by Joungkyun** [comment]
[2.0.1](https://github.com/OOPS-ORG-PHP/Lunar/releases/tag/2.0.1) 버전에서 KASI-Lunar 패키지를 이용하여, 천문과학연구권의 절기 데이터를 이용하실 수 있습니다. (2004~2026 기간)

**Comment by kunwis** [comment]
> [2.0.1](https://github.com/OOPS-ORG-PHP/Lunar/releases/tag/2.0.1) 버전에서 KASI-Lunar 패키지를 이용하여, 천문과학연구권의 절기 데이터를 이용하실 수 있습니다. (2004~2026 기간)

네...노고에 감사드립니다. 
그런데 폴더에 천문과학연구원 API파일은 없는것 같은데...
자체 포함되어 있는지요?
오늘도 즐겁고 행복한 하루되세요~

**Comment by Joungkyun** [comment]
@kunwis 

천문과학연구원의 데이터는 KASI-Lunar 에 들어 있습니다. Lunar package 는 KASI-Lunar package 가 설치되어 있을 경우, KASI-Lunar package를 이용하여 천문과학연구원의 데이터를 이용하게 됩니다.

그 외에, 절기 데이터 업데이트 하면서 버그가 발견이 되어, 다음 버전으로 새로 릴리즈를 했으니 참고 하세요.

[KSAI-Lunar](https://github.com/OOPS-ORG-PHP/KASI-Lunar) [2.0.1](https://github.com/OOPS-ORG-PHP/KASI-Lunar/releases/tag/2.0.1)
Lunar [2.0.2](https://github.com/OOPS-ORG-PHP/Lunar/releases/tag/2.0.2)

**Comment by Joungkyun** [comment]
> 더운날 노고가 많으십니다. 친절한 답변 감사드리오며 조금더 다듬어 지면 아주 훌륭한 작품이 될것 같네요. 프로그램을 뜯어봐도 뭔지는 몰라도 두분다 존경스럽습니다. fullcalendar 라이브러리에 적용해 보고 있는데 2050년 이전에는 0.15초 이던게 넘어가니 달을 넘기면 응답속도가 1초를 넘어 버리네요.

https://oops.org/project/manse 를 보시면 알겠지만, 2200년까지는 성능이 떨어지지 않습니다. 그 이후는 조금씩 떨어집니다.
fullcalendar의 성능이 2050년 이후 부터 떨어지든지, 아니면 음력 외의 절기/세차/일진 등등의 여러 정보들을 가져오면서 성능이 떨어질 수도 있을 것 같습니다.

특히, 일진을 구하기 위해 dayfortune method 를 사용할 경우 그냥 loop 를 돌리면 성능이 별로 좋지 않습니다. 다음 코드를 참조 하세요

```php
<?php

/*
 * 7월 1일 부터 30일 까지의 일진을 구할 경우
 * 다음은 아주 안좋은 방법이다.
 */

for ( $i=1; $i<31; $i++ ) {
    $r = $lunar->dayfortune ('2013-07-' . $i);
    $iljin[$i] = $r->day;
}

/*
 * 위의 경우는 아래와 같이 $lunar->ganji_ref method를 이용하여
 * 성능을 높일 수 있다.
 */

$r = $lunar->dayfortune ('2013-07-01');
$iljin[$i] = $r->day;
$gindex = $r->data->d;

for ( $i=2; $i<31; $i++ ) {
    $gindex++;
    if ( $gindex >= 60 )
        $gindex -= 60;
    $iljin[$i] = $lunar->ganji_ref[$gindex];
}
?>
```

**Comment by kunwis** [comment]
> > 더운날 노고가 많으십니다. 친절한 답변 감사드리오며 조금더 다듬어 지면 아주 훌륭한 작품이 될것 같네요. 프로그램을 뜯어봐도 뭔지는 몰라도 두분다 존경스럽습니다. fullcalendar 라이브러리에 적용해 보고 있는데 2050년 이전에는 0.15초 이던게 넘어가니 달을 넘기면 응답속도가 1초를 넘어 버리네요.
> 
> https://oops.org/project/manse 를 보시면 알겠지만, 2200년까지는 성능이 떨어지지 않습니다. 그 이후는 조금씩 떨어집니다. fullcalendar의 성능이 2050년 이후 부터 떨어지든지, 아니면 음력 외의 절기/세차/일진 등등의 여러 정보들을 가져오면서 성능이 떨어질 수도 있을 것 같습니다.
> 
> 특히, 일진을 구하기 위해 dayfortune method 를 사용할 경우 그냥 loop 를 돌리면 성능이 별로 좋지 않습니다. 다음 코드를 참조 하세요
> 
> ```
> <?php
> 
> /*
>  * 7월 1일 부터 30일 까지의 일진을 구할 경우
>  * 다음은 아주 안좋은 방법이다.
>  */
> 
> for ( $i=1; $i<31; $i++ ) {
>     $r = $lunar->dayfortune ('2013-07-' . $i);
>     $iljin[$i] = $r->day;
> }
> 
> /*
>  * 위의 경우는 아래와 같이 $lunar->ganji_ref method를 이용하여
>  * 성능을 높일 수 있다.
>  */
> 
> $r = $lunar->dayfortune ('2013-07-01');
> $iljin[$i] = $r->day;
> $gindex = $r->data->d;
> 
> for ( $i=2; $i<31; $i++ ) {
>     $gindex++;
>     if ( $gindex >= 60 )
>         $gindex -= 60;
>     $iljin[$i] = $lunar->ganji_ref[$gindex];
> }
> ?>
> ```

감사합니다. 바로 적용하였습니다.

30
음력 : 3월 20일
평달 | 28수:방(房)
일진 : 을유(乙酉)
일별띠 : 닭[유:酉]
별자리 : 황소자리
꽃말 : 금사슬나무
손없는 날
....................................
달력에 출력하는 정보입니다.
일별띠나 별자리 꽃말, 손없는 날 이런것들은 배열에 담아두고 해당월이나 일자에 데이터를 가져와 뿌리는 정도인데...
2050년 전에는 평균 0.14초 정도이던것이 1초대를 넘어가 버리네요.
루프 안에는 최대한 반복하지 않으려고 바깥쪽에서 월단위로 가져올 데이터는 함수 한개로 모두 배열에 담아두엇다가
달력 루프를 돌면서 뿌리는데 왠 시간이 그렇게 걸리는지... ㅠㅠ
하나하나 주석처리 하면서 테스트해보니... 음력 변환에서 가장 많은 시간이 걸리는것 같네요.
좀더 커스트마이징해보면서 시간을 줄여봐야 겠습니다.
즐거운 주말 보내세요. 감사합니다.
